### ISSUE TITLE
Develop upgradable hoverboard parts

### ISSUE THREAD

**Issue by MatthewTeolis** [KKMMMTTT/AstroSoar#30]
**Tasks**
- [ ] Define list of parts for hoverboard
- [ ] Create hoverboard parts
- [ ] Design upgrading logic
- [ ] Integrate parts into hoverboard
- [ ] Integrate hoverboard into player movement

**Acceptance Criteria**
Using the debug tool, add commands that would add/upgrade/remove hoverboard parts.

**Comment by kwreen** [comment]
List of hoverboard parts:
- Side wings
- Tail wing
- Material build
- Thruster
